Read all the problem statements, notes carefully and scrape the required data using any web scraping tool of your choice.
• You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-element- exception/38023345




1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [ ]:
#Extracting Rank
rank=[i.text.strip('.') for i in driver.find_elements(By.XPATH,'//tbody/tr/td[1]')[:30]]

#Extracting Name
name =[i.text.split('[')[0] for i in driver.find_elements(By.XPATH,'//tr/td[2]')[:30]]

#Extracting Artist
artist = [i.text for i in driver.find_elements(By.XPATH,'//tr/td[3]')[:30]]

#extracting views
viewsBillions =[i.text for i in driver.find_elements(By.XPATH,'//tr/td[4]')[:30]]

#extracting Upload Date
uploadDate=[i.text for i in driver.find_elements(By.XPATH,'//tr/td[5]')[:30]]

driver.close()

print(len(rank),len(name),len(artist),len(viewsBillions),len(uploadDate))

30 30 30 30 30

In [ ]:
Most_viewed_videos_on_YouTube = pd.DataFrame({
    "Rank":rank,
    "Name": name,
    "Artist": artist,
    "Upload Date": uploadDate,
    "Views In Billions": viewsBillions
})

#set rank as index
Most_viewed_videos_on_YouTube = Most_viewed_videos_on_YouTube.set_index('Rank')
Most_viewed_videos_on_YouTube

,Name,Artist,Upload Date,Views In Billions
Rank,,,,
,This section's factual accuracy may be comprom...,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",13.48
1,"""Baby Shark Dance""",Luis Fonsi,"January 12, 2017",8.28
2,"""Despacito""",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.82
3,"""Johny Johny Yes Papa""",Cocomelon - Nursery Rhymes,"May 2, 2018",6.45
4,"""Bath Song""",Ed Sheeran,"January 30, 2017",6.11
5,"""Shape of You""",Wiz Khalifa,"April 6, 2015",6.05
6,"""See You Again""",Cocomelon - Nursery Rhymes,"May 24, 2018",5.62
7,"""Wheels on the Bus""",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.52
8,"""Phonics Song with Two Words""",Mark Ronson,"November 19, 2014",5.05
9,"""Uptown Funk""",Miroshka TV,"February 27, 2018",4.99
10,"""Learning Colors – Colorful Eggs on a Farm""",officialpsy,"July 15, 2012",4.92
11,"""Gangnam Style""",Get Movies,"January 31, 2012",4.56
12,"""Masha and the Bear – Recipe for Disaster""",Ultra Records,"April 5, 2018",4.46
13,"""Dame Tu Cosita""",Crazy Frog,"June 16, 2009",4.09
14,"""Axel F""",Maroon 5,"January 14, 2015",3.95
15,"""Sugar""",OneRepublic,"May 31, 2013",3.89
16,"""Counting Stars""",Katy Perry,"September 5, 2013",3.89
17,"""Roar""",Cocomelon - Nursery Rhymes,"June 25, 2018",3.80
18,"""Baa Baa Black Sheep""",Shakira,"June 4, 2010",3.75
19,"""Waka Waka (This Time for Africa)""",Justin Bieber,"October 22, 2015",3.72
20,"""Sorry""",Jingle Toons,"June 14, 2018",3.71
21,"""Lakdi Ki Kathi""",Ed Sheeran,"October 7, 2014",3.67
22,"""Thinking Out Loud""",Katy Perry,"February 20, 2014",3.60
23,"""Dark Horse""",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.58
24,"""Humpty the train on a fruits ride""",Ed Sheeran,"November 9, 2017",3.56
25,"""Perfect""",Passenger,"July 25, 2012",3.53
26,"""Let Her Go""",Alan Walker,"December 3, 2015",3.53
27,"""Faded""",Maroon 5,"May 31, 2018",3.50
28,"""Girls Like You""",T-Series Bhakti Sagar,"May 10, 2011",3.48
29,"""Shree Hanuman Chalisa""",Major Lazer Official,"March 22, 2015",3.48

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window

# URL of the BCCI website
url = "https://www.bcci.tv/"

# Navigate to the BCCI website
driver.get(url)

In [ ]:


fixtures_link = driver.find_element(By.XPATH, '//*[@id="pills-international-tab"]')
fixtures_link.click()

# Wait for the International Fixtures page to load
driver.implicitly_wait(10)  # Adjust the waiting time as needed

# Create lists to store the scraped data
series_list = []
place_list = []
date_list = []
time_list = []

# Find and extract details of international fixtures
fixtures = driver.find_elements(By.CSS_SELECTOR, "li.js-list")

for fixture in fixtures:
    series = fixture.find_element(By.CLASS_NAME, "fixture__format").text
    place = fixture.find_element(By.CLASS_NAME, "fixture__additional-info").find_element(By.TAG_NAME, "span").text
    date = fixture.find_element(By.CLASS_NAME, "fixture__date").text
    time = fixture.find_element(By.CLASS_NAME, "fixture__time").text

    series_list.append(series)
    place_list.append(place)
    date_list.append(date)
    time_list.append(time)

# Create a DataFrame
data = {
    "Series": series_list,
    "Place": place_list,
    "Date": date_list,
    "Time": time_list
}
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

# Close the WebDriver
driver.quit()

Empty DataFrame
Columns: [Series, Place, Date, Time]
Index: []

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
#opening the website page
driver.get("https://www.statisticstimes.com/")

In [ ]:

#clicking Economy
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()

#Clicking on India
india=driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india.click()

In [ ]:
GDP=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

In [ ]:
#Extracting the details
rank = []
state = []
gsdp_18 = []
gsdp_19 = []
shares = []
gdp = []

#Extracting the rank details
try:
    rank_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[1]")
    for ra in rank_tags:
        rank.append(ra.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting state name details
try:
    state_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[2]")
    for st in state_tags:
        state.append(st.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting gsdp 2019-20
try:
    gsdp_19_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[3]")
    for g in gsdp_19_tags:
        gsdp_19.append(g.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting gsdp 2018-19
try:
    gsdp_18_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[4]")
    for gs in gsdp_18_tags:
        gsdp_18.append(gs.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting share details
try:
    shares_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[5]")
    for sh in shares_tags:
        shares.append(sh.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting GDP details
try:
    gdp_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[6]")
    for gd in gdp_tags:
        gdp.append(gd.text)
except NoSuchElementException:
    Company.append('NA')

gdp_india = pd.DataFrame({'Rank':rank,'State':state,'GSDP 2019-20(Cr INR at Current Price)':gsdp_19,'GSDP 2018-19(Cr INR at Current Price)':gsdp_18,'Share(%)':shares,'GDP($billion)':gdp})
gdp_india

,Rank,State,GSDP 2019-20(Cr INR at Current Price),GSDP 2018-19(Cr INR at Current Price),Share(%),GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

4. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details:
Repository title
Repository description
Contributors count
Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
#opening the website page
driver.get("https://github.com/")

In [ ]:
#Clicking Open Source
source =driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
source.click()

#clicking Trending
trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [ ]:
#Extracting title
title=[i.text for i in driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')]

#Extracting Description
description = []

for item in driver.find_elements(By.XPATH, '//article[@class="Box-row"]'):
    try:
        des = item.find_element(By.XPATH, './/p[@class="col-9 color-fg-muted my-1 pr-4"]')
        description.append(des.text)
    except NoSuchElementException:
        description.append('-')

#Extracting Contributors count
count=[i.text for i in driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/a')]
contri=count[::2]

#Extracting Language
lang = []
for items in driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]'):
    try:
        l= items.find_element(By.XPATH,'./span/span[2]')
        lang.append(l.text)
    except NoSuchElementException:
        lang.append('-')

driver.close()
print(len(title), len(description), len(contri), len(lang))

#Converting it into DataFrame:
trending_repositories = pd.DataFrame({
    "Repository Title":title,
    "Repository Description": description,
    "Contributors Count" : contri,
    "Language" : lang
})

trending_repositories

25 25 25 25

,Repository Title,Repository Description,Contributors Count,Language
0,ByteByteGoHq / system-design-101,Explain complex systems using visuals and simp...,"15,723",-
1,localsend / localsend,An open source cross-platform alternative to A...,"17,425",Dart
2,Alex313031 / thorium,Chromium fork named after radioactive element ...,"2,179",C++
3,OpenBMB / XAgent,An Autonomous LLM Agent for Complex Task Solving,"2,072",TypeScript
4,lyswhut / lx-music-desktop,一个基于 electron 的音乐软件,"31,859",TypeScript
5,NVIDIA / Stable-Diffusion-WebUI-TensorRT,TensorRT Extension for Stable Diffusion Web UI,558,Python
6,epicweb-dev / full-stack-foundations,Learn the foundational skills of building full...,247,TypeScript
7,TheRealJoelmatic / RemoveAdblockThing,"Removes The ""Ad blocker are not allowed on You...","1,852",JavaScript
8,cloudcommunity / Free-Certifications,A curated list of free courses & certifications.,"9,552",-
9,wagtail / wagtail,A Django content management system focused on ...,"16,071",Python
10,cpacker / MemGPT,Teaching LLMs memory management for unbounded ...,"3,324",Python
11,0x48piraj / fadblock,"Friendly Adblock for YouTube: A fast, lightwei...",459,CSS
12,devfullcycle / imersao15,-,107,TypeScript
13,Azure-Samples / azure-search-openai-demo,A sample app for the Retrieval-Augmented Gener...,"3,887",Python
14,xlang-ai / OpenAgents,OpenAgents: An Open Platform for Language Agen...,669,Python
15,ProfSynapse / Synapse_CoR,-,"1,552",-
16,nodejs / node,Node.js JavaScript runtime ✨🐢🚀✨,"98,813",JavaScript
17,cockpit-project / cockpit,Cockpit is a web-based graphical interface for...,"9,315",C
18,ionic-team / ionic-framework,A powerful cross-platform UI toolkit for build...,"49,633",TypeScript
19,strapi / strapi,🚀 Strapi is the leading open-source headless C...,"56,767",JavaScript
20,JustArchiNET / ArchiSteamFarm,C# application with primary purpose of farming...,"9,892",C#
21,luosiallen / latent-consistency-model,Latent Consistency Models: Synthesizing High-R...,280,Python
22,espnet / espnet,End-to-End Speech Processing Toolkit,"7,152",Python
23,web-platform-tests / wpt,Test suites for Web platform specs — including...,"4,443",HTML
24,thuml / Time-Series-Library,A Library for Advanced Deep Time Series Models.,"1,843",Shell

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details:
Song name
Artist name
Last week rank
Peak rank
Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
#opening the website page
driver.get("https://www.billboard.com/")

In [ ]:
#Clicking on the menu
menu=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[1]/div[1]/button')
menu.click()

In [ ]:

#Clicking top 100
top = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
top.click()

In [ ]:
#Extracting Required Data
data=[i.text.split('\n') for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]')]

driver.close()

#Creating DataFrame:
columns = ['Song name', 'Artist Name', 'Last Weak Rank', 'Peak Rank', 'Weeks on Chart']

Top100 = pd.DataFrame(data, columns=columns)
Top100

,Song name,Artist Name,Last Weak Rank,Peak Rank,Weeks on Chart
0,First Person Shooter,Drake Featuring J. Cole,-,1,1
1,IDGAF,Drake Featuring Yeat,-,2,1
2,Virginia Beach,Drake,-,3,1
3,Paint The Town Red,Doja Cat,1,1,10
4,Calling For You,Drake Featuring 21 Savage,-,5,1
...,...,...,...,...,...
95,God Gave Me A Girl,Russell Dickerson,90,90,2
96,Y Lloro,Junior H,-,97,1
97,Telekinesis,Travis Scott Featuring SZA & Future,72,26,11
98,Seven,Jung Kook Featuring Latto,57,1,13
99,Stars Like Confetti,Dustin Lynch,89,89,2

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:

#opening the website page
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [ ]:
#Extracting Book Name
book =[i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')]

#Extracting Author Name
author = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')]

#Extracting Volumes sold
vol = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')]

#Extracting Publisher
pub = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')]

#Extracting Genre
gen = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')]

driver.close()
print(len(book),len(author),len(vol),len(pub), len(gen))

# Convertingin Dataframe:
Highest_selling_novels=pd.DataFrame({
    "Book Name": book,
    "Author Name":author,
    "Volumes sold":vol,
    "Publisher": pub,
    "Genre" : gen
})

Highest_selling_novels

100 100 100 100 100

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

7. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:
Name
Year span
Genre
Run time
Ratings
Votes

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
#opening the website page
driver.get("https://www.imdb.com/list/ls095964455/")

In [ ]:
#Extracting Name:
name =[i.text for i in driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')]

# Extracting Year Span
year = [i.text for i in driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')]

#Extracting Genre
genre = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')]

#Extracting Run time
time = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')]

#Extracting Rating
rating = [i.text for i in driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')]

#Extracting Votes
voting = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]')]

driver.close()
print(len(name), len(year), len(genre), len(time), len(rating),len(voting))

#Creating DataFrame
most_watched_tv_series=pd.DataFrame({
    "Name": name,
    "Year span":year,
    "Genre":genre,
    "Run time":time,
    "Ratings":rating,
    "Votes": voting
})
most_watched_tv_series

100 100 100 100 100 100

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,213,725"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,283,471"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,050,517"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"308,652"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"267,590"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,963"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"65,030"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,950"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"44,116"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"270,325"

8. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details:
Dataset name
Data type
Task
Attribute type
No of instances
No of attribute
Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [ ]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import warnings
warnings.filterwarnings("ignore")

import time
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [ ]:
#opening the website page
driver.get("https://archive.ics.uci.edu/")

In [ ]:
#clicking all dataset
dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/header/nav/ul/li[1]/a')
dataset.click()

In [ ]:
#Clicking collapse
collapse=driver.find_element(By.XPATH,'//label[@class="btn-primary btn-sm btn flex gap-2 rounded-full"]')
collapse.click()

In [ ]:
name=[]
datatype=[]
task=[]
instances=[]
no_attribute=[]
attributetype=[]
year=[]

while True:

    #Extracting Name:
    for i in driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]'):
        name.append(i.text)

    #Extracting DataType
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[2]'):
        datatype.append(i.text)

    #Extracting task
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[1]'):
        task.append(i.text)

    #Extracting attribute
    try:
        for i in driver.find_elements(By.XPATH,'//tbody[@class="border"]/tr/td[2]'):
            attributetype.append(i.text)
    except (NoSuchElementException, StaleElementReferenceException):
        attributetype.append('N/A')

    #Extracting instances
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[3]'):
        instances.append(i.text)

    #Extracting No of attributes
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[4]'):
        no_attribute.append(i.text)

    #Extracting attribute
    for i in driver.find_elements(By.XPATH,'//div[@class="grid grid-cols-8 overflow-x-auto"]'):
        try:
            a=i.find_element(By.XPATH,'./table/tbody/tr/td[2]')
            attributetype.append(a.text)
        except NoSuchElementException:
            attributetype.append('N/A')

    #Extracting Year
    for i in driver.find_elements(By.XPATH,'//div[@class="grid grid-cols-8 overflow-x-auto"]'):
        try:
            y= i.find_element(By.XPATH,'./table/tbody/tr/td[3]')
            year.append(y.text)
        except NoSuchElementException:
            year.append('N/A')

    #clicking next button
    try:
        nextButton= driver.find_element(By.XPATH,'//button[@class="btn-primary btn-sm btn"][2]')
        nextButton.click()
        time.sleep(3)
    except (NoSuchElementException, ElementClickInterceptedException):
        break

driver.close()
Attributetype=attributetype[:10]
no_attribute=no_attribute[:10]
print(len(name),len(datatype),len(task),len(instances),len(no_attribute), len(Attributetype), len(year))

#Creating DataFrame:
data=pd.DataFrame({
    "Dataset Name":name,
    "Data Type":datatype,
    "Task":task,
    "Attribute Type":Attributetype,
    "No of Instances":instances,
    "No of Attribute":no_attribute,
    "Year":year})
data

10 10 10 10 10 10 10

,Dataset Name,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Iris,Tabular,Classification,Real,150 Instances,4 Features,7/1/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303 Instances,13 Features,7/1/1988
2,Adult,Multivariate,Classification,"Categorical, Integer",48.84K Instances,14 Features,5/1/1996
3,Wine,Tabular,Classification,"Integer, Real",178 Instances,13 Features,7/1/1991
4,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569 Instances,30 Features,11/1/1995
5,Diabetes,,,"Categorical, Integer",,20 Features,N/A
6,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13.61K Instances,16 Features,9/14/2020
7,Car Evaluation,Multivariate,Classification,Categorical,1.73K Instances,6 Features,6/1/1997
8,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3.81K Instances,8 Features,10/6/2019
9,Wine Quality,Multivariate,"Classification, Regression",Real,4.9K Instances,12 Features,10/7/2009